name: go_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  http: ^1.3.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  expandable_page_view: ^1.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  mockito: ^5.4.5
  json_serializable: ^6.9.3
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/apimock.json
  fonts:
    - family: Titillium
      fonts:
        - asset: assets/fonts/Titillium-Black.otf
          weight: 900
        - asset: assets/fonts/Titillium-Bold.otf
          weight: 700
        - asset: assets/fonts/Titillium-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Titillium-Semibold.otf
          weight: 600
        - asset: assets/fonts/Titillium-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Titillium-Regular.otf
          weight: 400
        - asset: assets/fonts/Titillium-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Titillium-Light.otf
          weight: 300
        - asset: assets/fonts/Titillium-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Titillium-Thin.otf
          weight: 100
        - asset: assets/fonts/Titillium-ThinItalic.otf
          weight: 100
          style: italic